### ISSUE TITLE
the plugin seems to ignore "toolVersion = '2.2.0'" and use its own older version of Gatling, which leads to compilation errors

### ISSUE THREAD

**Issue by alexeyOnGitHub** [lkishalmi/gradle-gatling-plugin#16]
hi guys!
I keep getting various compilation errors for gradle & gatling. is there a full valid build.gradle sample file somewhere that would work for the current Gatling version (2.2.0)?

looks like the plugin brings its own version of gatling which is different from 
1) the one I added: gatlingCompile 'io.gatling:gatling-core:2.2.0'
2) and also different from the one I set in "gatling" section: 
    gatling {
        toolVersion = '2.2.0'
    }

**Comment by eshepelyuk** [comment]
* I think the issue title is improper, could you please fix it ?
* You only need to set
```
gatling {
    toolVersion = '2.2.0'
}
```
There's no need to add dependencies to `gatlingCompile` configuration.

* Plugin was not tested with `2.2.0` version. It seems `Gatling` team recently released it. So I try to take a look to make the plugin work with latest `Gatling` version.

**Comment by alexeyOnGitHub** [comment]
if I add 

gatling {
    toolVersion = '2.2.0'
}

and remove "gatlingCompile 'io.gatling:gatling-core:2.2.0'" , then the plugin loads older version of Gradle as I see in "gradle dependencies" output:

> compile - Compile classpath for source set 'main'.
> \--- org.scala-lang:scala-library:2.11.8
> 
> default - Configuration for default artifacts.
> \--- org.scala-lang:scala-library:2.11.8
> 
> gatling
> \--- io.gatling.highcharts:gatling-charts-highcharts:2.1.7
>      +--- org.scala-lang:scala-library:2.11.7
>      +--- io.gatling:gatling-charts:2.1.7
>      |    +--- org.scala-lang:scala-library:2.11.7
>      |    +--- io.gatling:gatling-core:2.1.7
>

**Comment by eshepelyuk** [comment]
Confirming this as a bug.

**Comment by eshepelyuk** [comment]
Hello @alexeyOnGitHub 
Version `0.3.0` of the plugin was released, containing fixes for this bug and #17 as well.

**Comment by alexeyOnGitHub** [comment]
thank you guys!

I have another issue now: neither Gatling nor my project dependencies are not found during compilation. can you please add a complete sample  build.gradle file to use?

here's mine:

```
plugins {
    id "com.github.lkishalmi.gatling" version "0.3.0"
}

dependencies {
    compile 'org.scala-lang:scala-library:2.11.8'
    gatlingCompile("com.mycompany.loadtests:framework:0.9.2") {
        exclude module: "*"
    }
}

gatling {
    toolVersion = '2.2.0'
}

repositories {
    maven {
        url 'http://server:8081/artifactory/repos'
    }
}

```

and the current output from "gradle gatling" (or "gradle build") is:

> object gatling is not a member of package io
> import io.gatling.core.structure.ScenarioBuilder
>           ^
> object gatling is not a member of package io
> import io.gatling.http.Predef._
>           ^
> not found: type Simulation 
> class CreateAnonymousMediaSimulation extends Simulation {
>                                              ^
> not found: value tsv
>   val ownerIds = tsv("owner_ids." + serverEnvironment + ".tsv").circular
>

**Comment by eshepelyuk** [comment]
Could you please try to do following
1. remove `scala` from `compile` dependencies
2. remove `gatling` configuration closure

**Comment by alexeyOnGitHub** [comment]
this is with Gradle 2.12.

without the scala compile dependency and gatling "2.2.0" I get:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Cannot infer Scala class path because no Scala library Jar was found. Does root project 'services-media-performance-tests' declare dependency to scala-library? Searched classpath: file collection.
>

**Comment by eshepelyuk** [comment]
Ok, please downgrade `Gradle` to 2.11. I expirience strange issues in `IDEA` with `Gradle 2.12` too.

**Comment by alexeyOnGitHub** [comment]
downloaded Gradle 2.12, tried with it. same error message about missing Scala

**Comment by eshepelyuk** [comment]
You need to try **2.11**, not *2.12*

**Comment by eshepelyuk** [comment]
Well, may you attach project archive ?

**Comment by alexeyOnGitHub** [comment]
I understand that having a complete project would be very helpful, but this is company property, not mine.  cannot share the whole thing. plus it would not work outside of VPN because it loads an internal dependency ("framework") from a binary storage. I hope you understand.. that framework has a few Scala classes used by all load tests (minimal configuration, etc).

do you believe that the last build.gradle snippet you provided should work with gradle 2.11-2.12?
having a complete example posted in README.md would be awesome

**Comment by eshepelyuk** [comment]
Unfortunately I can't help you without additional details, i.e. project structure. Since it seems there shouldn't be any reasons for compilation errors. In fact, the only thing to startup is to apply plugin for the build script, no additional steps required.

Is ti possible to strip out proprietary classes and just send the skeleton with some basic `Simulation`, so I can try to reproduce

**Comment by alexeyOnGitHub** [comment]
here is the stripped version that still gives the same compilation error: https://bitbucket.org/alskor/perftests-demo/downloads/performance-tests.zip

**Comment by eshepelyuk** [comment]
Well, I see what the problem is. Basically, your simulation classes are located in wrong directory.
Please check `README` for detailed description of supported layouts.

**Comment by alexeyOnGitHub** [comment]
alright, I see renaming "/src/test" to "/src/gatling" gets me through this issue. thanks!
I tried "/src/gatling" yesterday but then reverted back because I wasn't ready to switch from maven to this plugin :)

the error message about missing scala dependency in the build while sources are not found in the "right" folder seems misleading and not quite valid, what do you think?

**Comment by eshepelyuk** [comment]
That error message has nothing to do with this plugin. It is produced by `Gradle` itself when it's trying to compile sources that are not properly configured (i.e. no scala plugin was applied and no proper dependencies was declared in your case).

In fact `Gatling` plugin will not even try to compile anything if there's no sources found in expected place.

**Comment by alexeyOnGitHub** [comment]
alright, thank you. I will move the code to /src/gatling . it's a bit unexpected that "/src/test/" is not accepted by Gatling as a standard location
